title: Xian Xu
email: first_name.last_name@gmail.com
description: >
  Personal thoughts on current events, society and technology.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xianxu.github.io"
twitter_username: xianxu
github_username:  xianxu

minima:
  skin: solarized-light

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-relative-links

relative_links:
  collections: true
  enabled: true

header_pages:
  - archive.html
  - about.markdown

social:
  linkedin: xianxu

google_analytics: G-CY33L153PE

markdown: kramdown
kramdown:
  parse_block_html: true
  parse_span_html: true
  footnote_nr: 1
  footnote_backlink: "&#8617;&#xfe0e;"
  enable_coderay: false
  auto_ids: true
  auto_id_stripping: true
